cp -vp ./libs/gd/Makefile.in ./libs/gd/Makefile.in.tmp  && sed -f ${SED_MK} ./libs/gd/Makefile.in.tmp > ./libs/gd/Makefile.in
cp -vp ./libs/libpng/Makefile.in ./libs/libpng/Makefile.in.tmp  && sed -f ${SED_MK} ./libs/libpng/Makefile.in.tmp > ./libs/libpng/Makefile.in
cp -vp ./libs/ncurses/include/Makefile.in ./libs/ncurses/include/Makefile.in.tmp  && sed -f ${SED_MK} ./libs/ncurses/include/Makefile.in.tmp > ./libs/ncurses/include/Makefile.in
cp -vp ./libs/ncurses/Makefile.in ./libs/ncurses/Makefile.in.tmp  && sed -f ${SED_MK} ./libs/ncurses/Makefile.in.tmp > ./libs/ncurses/Makefile.in
cp -vp ./libs/ncurses/man/Makefile.in ./libs/ncurses/man/Makefile.in.tmp  && sed -f ${SED_MK} ./libs/ncurses/man/Makefile.in.tmp > ./libs/ncurses/man/Makefile.in
cp -vp ./libs/ncurses/ncurses/Makefile.in ./libs/ncurses/ncurses/Makefile.in.tmp  && sed -f ${SED_MK} ./libs/ncurses/ncurses/Makefile.in.tmp > ./libs/ncurses/ncurses/Makefile.in
cp -vp ./libs/t1lib/Makefile.in ./libs/t1lib/Makefile.in.tmp  && sed -f ${SED_MK} ./libs/t1lib/Makefile.in.tmp > ./libs/t1lib/Makefile.in
cp -vp ./libs/type1/Makefile.in ./libs/type1/Makefile.in.tmp  && sed -f ${SED_MK} ./libs/type1/Makefile.in.tmp > ./libs/type1/Makefile.in
cp -vp ./libs/xpdf/fofi/Makefile.in ./libs/xpdf/fofi/Makefile.in.tmp  && sed -f ${SED_MK} ./libs/xpdf/fofi/Makefile.in.tmp > ./libs/xpdf/fofi/Makefile.in
cp -vp ./libs/xpdf/goo/Makefile.in ./libs/xpdf/goo/Makefile.in.tmp  && sed -f ${SED_MK} ./libs/xpdf/goo/Makefile.in.tmp > ./libs/xpdf/goo/Makefile.in
cp -vp ./libs/xpdf/Makefile.in ./libs/xpdf/Makefile.in.tmp  && sed -f ${SED_MK} ./libs/xpdf/Makefile.in.tmp > ./libs/xpdf/Makefile.in
cp -vp ./libs/xpdf/xpdf/Makefile.in ./libs/xpdf/xpdf/Makefile.in.tmp  && sed -f ${SED_MK} ./libs/xpdf/xpdf/Makefile.in.tmp > ./libs/xpdf/xpdf/Makefile.in
cp -vp ./libs/zlib/Makefile.in ./libs/zlib/Makefile.in.tmp  && sed -f ${SED_MK} ./libs/zlib/Makefile.in.tmp > ./libs/zlib/Makefile.in
cp -vp ./Makefile.in ./Makefile.in.tmp  && sed -f ${SED_MK} ./Makefile.in.tmp > ./Makefile.in
cp -vp ./texk/dviljk/Makefile.in ./texk/dviljk/Makefile.in.tmp  && sed -f ${SED_MK} ./texk/dviljk/Makefile.in.tmp > ./texk/dviljk/Makefile.in
cp -vp ./texk/dvipdfm/Makefile.in ./texk/dvipdfm/Makefile.in.tmp  && sed -f ${SED_MK} ./texk/dvipdfm/Makefile.in.tmp > ./texk/dvipdfm/Makefile.in
cp -vp ./texk/dvipng/Makefile.in ./texk/dvipng/Makefile.in.tmp  && sed -f ${SED_MK} ./texk/dvipng/Makefile.in.tmp > ./texk/dvipng/Makefile.in
cp -vp ./texk/dvipsk/Makefile.in ./texk/dvipsk/Makefile.in.tmp  && sed -f ${SED_MK} ./texk/dvipsk/Makefile.in.tmp > ./texk/dvipsk/Makefile.in
cp -vp ./texk/gsftopk/Makefile.in ./texk/gsftopk/Makefile.in.tmp  && sed -f ${SED_MK} ./texk/gsftopk/Makefile.in.tmp > ./texk/gsftopk/Makefile.in
cp -vp ./texk/kpathsea/Makefile.in ./texk/kpathsea/Makefile.in.tmp  && sed -f ${SED_MK} ./texk/kpathsea/Makefile.in.tmp > ./texk/kpathsea/Makefile.in
cp -vp ./texk/Makefile.in ./texk/Makefile.in.tmp  && sed -f ${SED_MK} ./texk/Makefile.in.tmp > ./texk/Makefile.in
cp -vp ./texk/makeindexk/Makefile.in ./texk/makeindexk/Makefile.in.tmp  && sed -f ${SED_MK} ./texk/makeindexk/Makefile.in.tmp > ./texk/makeindexk/Makefile.in
cp -vp ./texk/ps2pkm/Makefile.in ./texk/ps2pkm/Makefile.in.tmp  && sed -f ${SED_MK} ./texk/ps2pkm/Makefile.in.tmp > ./texk/ps2pkm/Makefile.in
cp -vp ./texk/tetex/Makefile.in ./texk/tetex/Makefile.in.tmp  && sed -f ${SED_MK} ./texk/tetex/Makefile.in.tmp > ./texk/tetex/Makefile.in
cp -vp ./texk/web2c/doc/Makefile.in ./texk/web2c/doc/Makefile.in.tmp  && sed -f ${SED_MK} ./texk/web2c/doc/Makefile.in.tmp > ./texk/web2c/doc/Makefile.in
cp -vp ./texk/web2c/lib/Makefile.in ./texk/web2c/lib/Makefile.in.tmp  && sed -f ${SED_MK} ./texk/web2c/lib/Makefile.in.tmp > ./texk/web2c/lib/Makefile.in
cp -vp ./texk/web2c/Makefile.in ./texk/web2c/Makefile.in.tmp  && sed -f ${SED_MK} ./texk/web2c/Makefile.in.tmp > ./texk/web2c/Makefile.in
cp -vp ./texk/web2c/man/Makefile.in ./texk/web2c/man/Makefile.in.tmp  && sed -f ${SED_MK} ./texk/web2c/man/Makefile.in.tmp > ./texk/web2c/man/Makefile.in
cp -vp ./texk/web2c/mpware/Makefile.in ./texk/web2c/mpware/Makefile.in.tmp  && sed -f ${SED_MK} ./texk/web2c/mpware/Makefile.in.tmp > ./texk/web2c/mpware/Makefile.in
cp -vp ./texk/web2c/omegafonts/Makefile.in ./texk/web2c/omegafonts/Makefile.in.tmp  && sed -f ${SED_MK} ./texk/web2c/omegafonts/Makefile.in.tmp > ./texk/web2c/omegafonts/Makefile.in
cp -vp ./texk/web2c/otps/Makefile.in ./texk/web2c/otps/Makefile.in.tmp  && sed -f ${SED_MK} ./texk/web2c/otps/Makefile.in.tmp > ./texk/web2c/otps/Makefile.in
cp -vp ./texk/web2c/pdfetexdir/Makefile.in ./texk/web2c/pdfetexdir/Makefile.in.tmp  && sed -f ${SED_MK} ./texk/web2c/pdfetexdir/Makefile.in.tmp > ./texk/web2c/pdfetexdir/Makefile.in
cp -vp ./texk/web2c/pdftexdir/Makefile.in ./texk/web2c/pdftexdir/Makefile.in.tmp  && sed -f ${SED_MK} ./texk/web2c/pdftexdir/Makefile.in.tmp > ./texk/web2c/pdftexdir/Makefile.in
cp -vp ./texk/web2c/pdfxtexdir/Makefile.in ./texk/web2c/pdfxtexdir/Makefile.in.tmp  && sed -f ${SED_MK} ./texk/web2c/pdfxtexdir/Makefile.in.tmp > ./texk/web2c/pdfxtexdir/Makefile.in
cp -vp ./texk/web2c/web2c/Makefile.in ./texk/web2c/web2c/Makefile.in.tmp  && sed -f ${SED_MK} ./texk/web2c/web2c/Makefile.in.tmp > ./texk/web2c/web2c/Makefile.in
cp -vp ./texk/web2c/window/Makefile.in ./texk/web2c/window/Makefile.in.tmp  && sed -f ${SED_MK} ./texk/web2c/window/Makefile.in.tmp > ./texk/web2c/window/Makefile.in
cp -vp ./texk/xdvik/gui/Makefile.in ./texk/xdvik/gui/Makefile.in.tmp  && sed -f ${SED_MK} ./texk/xdvik/gui/Makefile.in.tmp > ./texk/xdvik/gui/Makefile.in
cp -vp ./texk/xdvik/Makefile.in ./texk/xdvik/Makefile.in.tmp  && sed -f ${SED_MK} ./texk/xdvik/Makefile.in.tmp > ./texk/xdvik/Makefile.in
cp -vp ./utils/dialog/Makefile.in ./utils/dialog/Makefile.in.tmp  && sed -f ${SED_MK} ./utils/dialog/Makefile.in.tmp > ./utils/dialog/Makefile.in
cp -vp ./utils/texi2html/doc/Makefile.in ./utils/texi2html/doc/Makefile.in.tmp  && sed -f ${SED_MK} ./utils/texi2html/doc/Makefile.in.tmp > ./utils/texi2html/doc/Makefile.in
cp -vp ./utils/texi2html/Makefile.in ./utils/texi2html/Makefile.in.tmp  && sed -f ${SED_MK} ./utils/texi2html/Makefile.in.tmp > ./utils/texi2html/Makefile.in
cp -vp ./utils/texi2html/Tests/Makefile.in ./utils/texi2html/Tests/Makefile.in.tmp  && sed -f ${SED_MK} ./utils/texi2html/Tests/Makefile.in.tmp > ./utils/texi2html/Tests/Makefile.in
cp -vp ./utils/texinfo/doc/Makefile.in ./utils/texinfo/doc/Makefile.in.tmp  && sed -f ${SED_MK} ./utils/texinfo/doc/Makefile.in.tmp > ./utils/texinfo/doc/Makefile.in
cp -vp ./utils/texinfo/info/Makefile.in ./utils/texinfo/info/Makefile.in.tmp  && sed -f ${SED_MK} ./utils/texinfo/info/Makefile.in.tmp > ./utils/texinfo/info/Makefile.in
cp -vp ./utils/texinfo/intl/Makefile.in ./utils/texinfo/intl/Makefile.in.tmp  && sed -f ${SED_MK} ./utils/texinfo/intl/Makefile.in.tmp > ./utils/texinfo/intl/Makefile.in
cp -vp ./utils/texinfo/lib/Makefile.in ./utils/texinfo/lib/Makefile.in.tmp  && sed -f ${SED_MK} ./utils/texinfo/lib/Makefile.in.tmp > ./utils/texinfo/lib/Makefile.in
cp -vp ./utils/texinfo/m4/Makefile.in ./utils/texinfo/m4/Makefile.in.tmp  && sed -f ${SED_MK} ./utils/texinfo/m4/Makefile.in.tmp > ./utils/texinfo/m4/Makefile.in
cp -vp ./utils/texinfo/Makefile.in ./utils/texinfo/Makefile.in.tmp  && sed -f ${SED_MK} ./utils/texinfo/Makefile.in.tmp > ./utils/texinfo/Makefile.in
cp -vp ./utils/texinfo/makeinfo/Makefile.in ./utils/texinfo/makeinfo/Makefile.in.tmp  && sed -f ${SED_MK} ./utils/texinfo/makeinfo/Makefile.in.tmp > ./utils/texinfo/makeinfo/Makefile.in
cp -vp ./utils/texinfo/makeinfo/tests/Makefile.in ./utils/texinfo/makeinfo/tests/Makefile.in.tmp  && sed -f ${SED_MK} ./utils/texinfo/makeinfo/tests/Makefile.in.tmp > ./utils/texinfo/makeinfo/tests/Makefile.in
cp -vp ./utils/texinfo/util/Makefile.in ./utils/texinfo/util/Makefile.in.tmp  && sed -f ${SED_MK} ./utils/texinfo/util/Makefile.in.tmp > ./utils/texinfo/util/Makefile.in
cp -vp ./libs/xpdf/fofi/Makefile.in ./libs/xpdf/fofi/Makefile.in.tmp && sed -f ${SED_MK1} ./libs/xpdf/fofi/Makefile.in.tmp > ./libs/xpdf/fofi/Makefile.in
cp -vp ./libs/xpdf/goo/Makefile.in ./libs/xpdf/goo/Makefile.in.tmp && sed -f ${SED_MK1} ./libs/xpdf/goo/Makefile.in.tmp > ./libs/xpdf/goo/Makefile.in
cp -vp ./utils/dialog/Makefile.in ./utils/dialog/Makefile.in.tmp && sed -f ${SED_MK1} ./utils/dialog/Makefile.in.tmp > ./utils/dialog/Makefile.in
cp -vp ./utils/texi2html/doc/Makefile.in ./utils/texi2html/doc/Makefile.in.tmp && sed -f ${SED_MK1} ./utils/texi2html/doc/Makefile.in.tmp > ./utils/texi2html/doc/Makefile.in
cp -vp ./utils/texi2html/Makefile.in ./utils/texi2html/Makefile.in.tmp && sed -f ${SED_MK1} ./utils/texi2html/Makefile.in.tmp > ./utils/texi2html/Makefile.in
cp -vp ./utils/texi2html/Tests/Makefile.in ./utils/texi2html/Tests/Makefile.in.tmp && sed -f ${SED_MK1} ./utils/texi2html/Tests/Makefile.in.tmp > ./utils/texi2html/Tests/Makefile.in
cp -vp ./utils/texinfo/doc/Makefile.in ./utils/texinfo/doc/Makefile.in.tmp && sed -f ${SED_MK1} ./utils/texinfo/doc/Makefile.in.tmp > ./utils/texinfo/doc/Makefile.in
cp -vp ./utils/texinfo/info/Makefile.in ./utils/texinfo/info/Makefile.in.tmp && sed -f ${SED_MK1} ./utils/texinfo/info/Makefile.in.tmp > ./utils/texinfo/info/Makefile.in
cp -vp ./utils/texinfo/intl/Makefile.in ./utils/texinfo/intl/Makefile.in.tmp && sed -f ${SED_MK1} ./utils/texinfo/intl/Makefile.in.tmp > ./utils/texinfo/intl/Makefile.in
cp -vp ./utils/texinfo/lib/Makefile.in ./utils/texinfo/lib/Makefile.in.tmp && sed -f ${SED_MK1} ./utils/texinfo/lib/Makefile.in.tmp > ./utils/texinfo/lib/Makefile.in
cp -vp ./utils/texinfo/m4/Makefile.in ./utils/texinfo/m4/Makefile.in.tmp && sed -f ${SED_MK1} ./utils/texinfo/m4/Makefile.in.tmp > ./utils/texinfo/m4/Makefile.in
cp -vp ./utils/texinfo/Makefile.in ./utils/texinfo/Makefile.in.tmp && sed -f ${SED_MK1} ./utils/texinfo/Makefile.in.tmp > ./utils/texinfo/Makefile.in
cp -vp ./utils/texinfo/makeinfo/Makefile.in ./utils/texinfo/makeinfo/Makefile.in.tmp && sed -f ${SED_MK1} ./utils/texinfo/makeinfo/Makefile.in.tmp > ./utils/texinfo/makeinfo/Makefile.in
cp -vp ./utils/texinfo/makeinfo/tests/Makefile.in ./utils/texinfo/makeinfo/tests/Makefile.in.tmp && sed -f ${SED_MK1} ./utils/texinfo/makeinfo/tests/Makefile.in.tmp > ./utils/texinfo/makeinfo/tests/Makefile.in
cp -vp ./utils/texinfo/util/Makefile.in ./utils/texinfo/util/Makefile.in.tmp && sed -f ${SED_MK1} ./utils/texinfo/util/Makefile.in.tmp > ./utils/texinfo/util/Makefile.in
cp -vp ./utils/texinfo/po/Makefile.in.in ./utils/texinfo/po/Makefile.in.in.tmp && sed -f ${SED_PO_MK} ./utils/texinfo/po/Makefile.in.in.tmp > ./utils/texinfo/po/Makefile.in.in
