cp -vp ./configure ./configure.tmp && sed -f ${SED_CONF} ./configure.tmp > ./configure
cp -vp ./libs/configure ./libs/configure.tmp && sed -f ${SED_CONF} ./libs/configure.tmp > ./libs/configure
cp -vp ./libs/gd/configure ./libs/gd/configure.tmp && sed -f ${SED_CONF} ./libs/gd/configure.tmp > ./libs/gd/configure
cp -vp ./libs/ncurses/configure ./libs/ncurses/configure.tmp && sed -f ${SED_CONF} ./libs/ncurses/configure.tmp > ./libs/ncurses/configure
cp -vp ./libs/t1lib/configure ./libs/t1lib/configure.tmp && sed -f ${SED_CONF} ./libs/t1lib/configure.tmp > ./libs/t1lib/configure
cp -vp ./libs/type1/configure ./libs/type1/configure.tmp && sed -f ${SED_CONF} ./libs/type1/configure.tmp > ./libs/type1/configure
cp -vp ./libs/xpdf/configure ./libs/xpdf/configure.tmp && sed -f ${SED_CONF} ./libs/xpdf/configure.tmp > ./libs/xpdf/configure
cp -vp ./texk/configure ./texk/configure.tmp && sed -f ${SED_CONF} ./texk/configure.tmp > ./texk/configure
cp -vp ./texk/dviljk/configure ./texk/dviljk/configure.tmp && sed -f ${SED_CONF} ./texk/dviljk/configure.tmp > ./texk/dviljk/configure
cp -vp ./texk/dvipdfm/configure ./texk/dvipdfm/configure.tmp && sed -f ${SED_CONF} ./texk/dvipdfm/configure.tmp > ./texk/dvipdfm/configure
cp -vp ./texk/dvipng/configure ./texk/dvipng/configure.tmp && sed -f ${SED_CONF} ./texk/dvipng/configure.tmp > ./texk/dvipng/configure
cp -vp ./texk/dvipsk/configure ./texk/dvipsk/configure.tmp && sed -f ${SED_CONF} ./texk/dvipsk/configure.tmp > ./texk/dvipsk/configure
cp -vp ./texk/gsftopk/configure ./texk/gsftopk/configure.tmp && sed -f ${SED_CONF} ./texk/gsftopk/configure.tmp > ./texk/gsftopk/configure
cp -vp ./texk/kpathsea/configure ./texk/kpathsea/configure.tmp && sed -f ${SED_CONF} ./texk/kpathsea/configure.tmp > ./texk/kpathsea/configure
cp -vp ./texk/ltmain.sh ./texk/ltmain.sh.tmp && sed -f ${SED_CONF} ./texk/ltmain.sh.tmp > ./texk/ltmain.sh
cp -vp ./texk/makeindexk/configure ./texk/makeindexk/configure.tmp && sed -f ${SED_CONF} ./texk/makeindexk/configure.tmp > ./texk/makeindexk/configure
cp -vp ./texk/ps2pkm/configure ./texk/ps2pkm/configure.tmp && sed -f ${SED_CONF} ./texk/ps2pkm/configure.tmp > ./texk/ps2pkm/configure
cp -vp ./texk/tetex/configure ./texk/tetex/configure.tmp && sed -f ${SED_CONF} ./texk/tetex/configure.tmp > ./texk/tetex/configure
cp -vp ./texk/web2c/configure ./texk/web2c/configure.tmp && sed -f ${SED_CONF} ./texk/web2c/configure.tmp > ./texk/web2c/configure
cp -vp ./texk/xdvik/configure ./texk/xdvik/configure.tmp && sed -f ${SED_CONF} ./texk/xdvik/configure.tmp > ./texk/xdvik/configure
cp -vp ./utils/dialog/configure ./utils/dialog/configure.tmp && sed -f ${SED_CONF} ./utils/dialog/configure.tmp > ./utils/dialog/configure
cp -vp ./utils/texi2html/configure ./utils/texi2html/configure.tmp && sed -f ${SED_CONF} ./utils/texi2html/configure.tmp > ./utils/texi2html/configure
cp -vp ./utils/texinfo/configure ./utils/texinfo/configure.tmp && sed -f ${SED_CONF} ./utils/texinfo/configure.tmp > ./utils/texinfo/configure
